version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-network

  api:
    build: .
    container_name: waiterapp-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongo:27017
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    volumes:
      # Mount source code for auto-reload
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./eslint.config.mts:/app/eslint.config.mts
      # Exclude node_modules to use the container's version
      - /app/node_modules

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
